apiVersion: v1
kind: Service
metadata:
  name: inter-app-service
  labels:
    app: inter-app-project
spec:
  selector:
    app: inter-app-project
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30180